### ISSUE TITLE
Compose examples do not work in JuliaBox

### ISSUE THREAD

**Issue by wbhart** [JuliaLang/JuliaBox#178] opened 2015-01-07 20:02 UTC
The examples on the webpage of the Compose package http://composejl.org/ do not work on JuliaBox. In particular the ones that use LCHab.

As this is pointed to as an example of plotting for use with JuliaBox, it's likely some of the first things people will try.

I didn't check into the cause. Perhaps Compose is not up-to-date on the VM instances, or perhaps there is something missing from the examples on the compose webpage, etc.

**Comment by tanmaykm** [comment] 2015-01-08 04:29
I get the following error, both on JuliaBox and on my local machine:
````
LCHab not defined
while loading In[4], in expression starting on line 1
````

This seems to be a bug in `Compose.jl`. `LCHab` is exported from `Color.jl`, but is probably not imported correctly in `Compose.jl`.

@wbhart Are you seeing the same error? You can avoid this error by having a `using Color` statement in your notebook, along with `using Compose`. This should probably be raised as an issue at https://github.com/dcjones/Compose.jl

**Comment by wbhart** [comment] 2015-01-08 04:32
Yes, that is the error I am getting.

**Comment by tanmaykm** [comment] 2015-01-08 04:38
OK. Then the workaround of including `using Color` should work for you too. I shall close the issue here. Please reopen if you face further issues.

Do you mind creating an issue at https://github.com/dcjones/Compose.jl for this?

**Closed by tanmaykm** 2015-01-08 04:38 UTC

**Comment by ViralBShah** [comment] 2015-01-08 05:08
This is not a bug then - just requires the right modules loaded.

**Comment by tanmaykm** [comment] 2015-01-08 05:10
Yes. The examples should probably mention the dependency though. Or I'm not sure if Compose can/should reexport `LCHab`.

**Comment by aviks** [comment] 2015-01-08 19:23
Doc change in PR: https://github.com/dcjones/Compose.jl/pull/106

**Comment by tanmaykm** [comment] 2015-01-09 03:39
Thanks @aviks !

**Comment by Teo-ShaoWei** [comment] 2016-04-12 14:25
I have a different example but it is under this title, so I am posting here. This is a screenshot of using compose on JuliaBox:-

![screenshot](https://cloud.githubusercontent.com/assets/6925907/14463334/2f143f06-00fd-11e6-8524-41375f967c1f.PNG)

I am unable to obtain a square and a full circle. All the drawings I did are also chopped off at the top and bottom... Could I have done my setup wrongly?
