### ISSUE TITLE
Julia 0.3.11 kernel keeps dying

### ISSUE THREAD

**Issue by mmagnuski** [JuliaLang/JuliaBox#306] opened 2015-10-07 17:39 UTC
I am experiencing frequent kernel deaths lately. Every time I launch Julia 0.3.11 notebook on juliabox the kernel is unable to start and dies. This happens only occasionally with Julia 0.4.0-rc2 notebooks (but many packages are still not compatible with 0.4 :( ).

**Comment by jiahao** [comment] 2015-10-07 17:53
Duplicate of #305

**Comment by tanmaykm** [comment] 2015-10-07 17:55
@mmagnuski  Could you also report the error IJulia throws? It is usually logged at `~/.juliabox/ijulia_err.log`

**Comment by mmagnuski** [comment] 2015-10-07 19:06
Contents of `ijulia_err.log` after kernel death:
```
[I 18:55:55.318 NotebookApp] Writing notebook server cookie secret to /home/juser/.ipython/profile_default/security/notebook_cookie_secret                                                                                                
[I 18:55:55.318 NotebookApp] Using MathJax from CDN: https://cdn.mathjax.org/mathjax/latest/MathJax.js                                                                                                                                    
[W 18:55:55.333 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.                                                                                             
[W 18:55:55.333 NotebookApp] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.                                                                     
[W 18:55:55.334 NotebookApp] Terminals not available (error was No module named terminado)                                                                                                                                                
[I 18:55:55.334 NotebookApp] Serving notebooks from local directory: /home/juser                                                                                                                                                          
[I 18:55:55.334 NotebookApp] 0 active kernels                                                                                                                                                                                             
[I 18:55:55.334 NotebookApp] The IPython Notebook is running at: http://[all ip addresses on your system]:8998/                                                                                                                           
[I 18:55:55.334 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).                                                                                                                    
[I 18:55:55.621 NotebookApp] 302 GET / (172.17.42.1) 0.66ms                                                                                                                                                                               
[I 18:55:55.622 NotebookApp] 302 GET / (172.17.42.1) 0.30ms                                                                                                                                                                               
[I 18:59:35.228 NotebookApp] Creating new notebook in                                                                                                                                                                                     
[I 18:59:35.230 NotebookApp] Writing notebook-signing key to /home/juser/.ipython/profile_default/security/notebook_secret                                                                                                                
[I 18:59:40.185 NotebookApp] Kernel started: 9a57a52d-2b45-459e-b892-860cca62f7b3                                                                                                                                                         
[W 18:59:40.193 NotebookApp] 404 GET /kernelspecs/julia-0.3/logo-64x64.png (172.17.42.1) 6.46ms referer=https://www.juliabox.org/notebooks/Untitled.ipynb?kernel_name=julia-0.3                                                           
ERROR: type: instantiate_type: expected TypeConstructor, got Function                                                                                                                                                                     
 in anonymous at no file:236                                                                                                                                                                                                              
 in include at ./boot.jl:245                                                                                                                                                                                                              
 in include_from_node1 at ./loading.jl:128                                                                                                                                                                                                
 in reload_path at loading.jl:152                                                                                                                                                                                                         
 in _require at loading.jl:67                                                                                                                                                                                                             
 in require at loading.jl:51                                                                                                                                                                                                              
 in include at ./boot.jl:245                                                                                                                                                                                                              
 in include_from_node1 at ./loading.jl:128                                                                                                                                                                                                
 in include at ./boot.jl:245                                                                                                                                                                                                              
 in include_from_node1 at loading.jl:128                                                                                                                                                                                                  
 in process_options at ./client.jl:285                                                                                                                                                                                                    
 in _start at ./client.jl:354                                                                                                                                                                                                             
while loading /opt/julia_packages/.julia/v0.3/ZMQ/src/ZMQ.jl, in expression starting on line 234                                                                                                                                          
while loading /opt/julia_packages/.julia/v0.3/IJulia/src/IJulia.jl, in expression starting on line 13                                                                                                                                     
while loading /opt/julia_packages/.julia/v0.3/IJulia/src/kernel.jl, in expression starting on line 4                                                                                                                                      
[I 18:59:43.186 NotebookApp] KernelRestarter: restarting kernel (1/5)                                                                                                                                                                     
ERROR: type: instantiate_type: expected TypeConstructor, got Function                                                                                                                                                                     
 in anonymous at no file:236                                                                                                                                                                                                              
 in include at ./boot.jl:245                                                                                                                                                                                                              
 in include_from_node1 at ./loading.jl:128                                                                                                                                                                                                
 in reload_path at loading.jl:152                                                                                                                                                                                                         
 in _require at loading.jl:67                                                                                                                                                                                                             
 in require at loading.jl:51                                                                                                                                                                                                              
 in include at ./boot.jl:245                                                                                                                                                                                                              
 in include_from_node1 at ./loading.jl:128                                                                                                                                                                                                
 in include at ./boot.jl:245                                                                                                                                                                                                              
 in include_from_node1 at loading.jl:128                                                                                                                                                                                                  
 in process_options at ./client.jl:285                                                                                                                                                                                                    
 in _start at ./client.jl:354                                                                                                                                                                                                             
while loading /opt/julia_packages/.julia/v0.3/ZMQ/src/ZMQ.jl, in expression starting on line 234                                                                                                                                          
while loading /opt/julia_packages/.julia/v0.3/IJulia/src/IJulia.jl, in expression starting on line 13                                                                                                                                     
while loading /opt/julia_packages/.julia/v0.3/IJulia/src/kernel.jl, in expression starting on line 4                                                                                                                                      
[I 18:59:46.191 NotebookApp] KernelRestarter: restarting kernel (2/5)                                                                                                                                                                     
ERROR: type: instantiate_type: expected TypeConstructor, got Function                                                                                                                                                                     
 in anonymous at no file:236
in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /opt/julia_packages/.julia/v0.3/ZMQ/src/ZMQ.jl, in expression starting on line 234
while loading /opt/julia_packages/.julia/v0.3/IJulia/src/IJulia.jl, in expression starting on line 13
while loading /opt/julia_packages/.julia/v0.3/IJulia/src/kernel.jl, in expression starting on line 4
[I 18:59:49.196 NotebookApp] KernelRestarter: restarting kernel (3/5)
[W 18:59:50.924 NotebookApp] Timeout waiting for kernel_info reply from 9a57a52d-2b45-459e-b892-860cca62f7b3
ERROR: type: instantiate_type: expected TypeConstructor, got Function
 in anonymous at no file:236
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /opt/julia_packages/.julia/v0.3/ZMQ/src/ZMQ.jl, in expression starting on line 234
while loading /opt/julia_packages/.julia/v0.3/IJulia/src/IJulia.jl, in expression starting on line 13
while loading /opt/julia_packages/.julia/v0.3/IJulia/src/kernel.jl, in expression starting on line 4
[I 18:59:52.200 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 9a57a52d-2b45-459e-b892-860cca62f7b3 restarted
ERROR: type: instantiate_type: expected TypeConstructor, got Function
 in anonymous at no file:236
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in reload_path at loading.jl:152
 in _require at loading.jl:67
 in require at loading.jl:51
 in include at ./boot.jl:245
 in include_from_node1 at ./loading.jl:128
 in include at ./boot.jl:245
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:285
 in _start at ./client.jl:354
while loading /opt/julia_packages/.julia/v0.3/ZMQ/src/ZMQ.jl, in expression starting on line 234
while loading /opt/julia_packages/.julia/v0.3/IJulia/src/IJulia.jl, in expression starting on line 13
while loading /opt/julia_packages/.julia/v0.3/IJulia/src/kernel.jl, in expression starting on line 4
[W 18:59:55.205 NotebookApp] KernelRestarter: restart failed
[W 18:59:55.206 NotebookApp] Kernel 9a57a52d-2b45-459e-b892-860cca62f7b3 died, removing from map.
ERROR:root:kernel 9a57a52d-2b45-459e-b892-860cca62f7b3 restarted failed!
[W 18:59:55.426 NotebookApp] Kernel deleted before session
[W 18:59:55.427 NotebookApp] 410 DELETE /api/sessions/76505f04-c5ec-4c61-a4e1-b5f63ec52e6f (172.17.42.1) 1.07ms referer=https://www.juliabox.org/notebooks/Untitled.ipynb?kernel_name=julia-0.3
```

**Comment by mmagnuski** [comment] 2015-10-07 19:15
Just as in #305 - removing `.julia` fixes the problem

**Comment by RobertoCarlos2** [comment] 2015-10-08 00:01
Would you please provide the instructions to remove .julia from the JuliaBox?

**Comment by tanmaykm** [comment] 2015-10-08 05:39
@RobertoCarlos2 just `rm -rf ~/.julia` should do it.

**Comment by RobertoCarlos2** [comment] 2015-10-08 11:41
Thank you @tanmaykm ! This seems to fix the problem.

**Closed** 2015-10-15 03:38 UTC

**Comment by Ismael-VC** [comment] 2015-12-27 08:40
removing `~/.julia` also works for versions 0.4.2 and 0.5+ which kernels where also kept dying.

**Comment by Ismael-VC** [comment] 2015-12-27 10:46
this also means we can't install anything anymore, After doing:

```julia
shell> rm -rf ~/.julia    # things work!

julia> Pkg.add("Gadfly")    # not anymore
```

Things break again.
